hicolor_dir = get_option('datadir') / 'icons' / 'hicolor'

install_data(
  'blind-x-16x16.png',
  install_dir: hicolor_dir / '16x16' / 'apps',
  rename: 'blind-x.png',
)

install_data(
  'blind-x-22x22.png',
  install_dir: hicolor_dir / '22x22' / 'apps',
  rename: 'blind-x.png',
)

install_data(
  'blind-x-24x24.png',
  install_dir: hicolor_dir / '24x24' / 'apps',
  rename: 'blind-x.png',
)

install_data(
  'blind-x-32x32.png',
  install_dir: hicolor_dir / '32x32' / 'apps',
  rename: 'blind-x.png',
)

install_data(
  'blind-x-48x48.png',
  install_dir: hicolor_dir / '48x48' / 'apps',
  rename: 'blind-x.png',
)

install_data(
  'blind-x-scalable.svg',
  install_dir: hicolor_dir / 'scalable' / 'apps',
  rename: 'blind-x.svg',
)

install_data(
  'blind-x-symbolic.svg',
  install_dir: hicolor_dir / 'symbolic' / 'apps',
)
